#cloud-config
users:
  - name: root
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILdkOvbTSi6UF9rSTJ+tkvPH02xLZJInKUwjxMyH6OAR bos.one@mail.ru